{
 "title": "bigzero-k8s",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "Pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info{namespace=~\"$Namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "노드 CPU 사용률",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) by (kubernetes_node)",
     "legendFormat": "{{ kubernetes_node }}"
    }
   ]
  },
  {
   "title": "노드 메모리 사용량",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 1 },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Active_bytes /1024/1024/1024",
     "legendFormat": "{{ kubernetes_node }}"
    }
   ]
  },
  {
   "title": "노드 네트워크 평균 송신/수신 트래픽",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_network_transmit_bytes_total[5m])) by (kubernetes_node)",
     "legendFormat": "{{ kubernetes_node }}"
    },
    {
     "expr": "avg(rate(node_network_transmit_bytes_total[5m])) by (kubernetes_node) * -1",
     "legendFormat": "{{ kubernetes_node }}-receive"
    }
   ]
  },
  {
   "title": "노드 상태",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"kubernetes-nodes\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "$Namespace Namespace Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "$Pod Pod 메모리 사용량",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~\"$Namespace\", pod=~\"$Pod\", container!=\"\"}) by (pod) /1024/1024/1024",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "$Pod Pod CPU 사용률",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$Namespace\", pod=~\"$Pod\", container!=\"\"}[5m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "API 서버 응답 시간(5분/SLA 99%)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Pod 상태",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{pod=~\"$Pod\", namespace=~\"$Namespace\"}) by (phase)",
     "legendFormat": "{{ phase }}"
    }
   ]
  }
 ]
}